import { useState } from "react";
import {
  approveDraft,
  generateContextDraft,
  getAuthMe,
  ingestEvidence,
  replayEvidence,
  runGhostPersona,
  submitDraftReview,
} from "./api";

const SAMPLE_EVENTS = [
  { ts: 1000, event_type: "keypress", payload: { chars: 12 } },
  { ts: 2200, event_type: "paste", payload: { chars: 80 } },
  { ts: 3500, event_type: "run_tests", payload: { passed: 3, failed: 2 } },
];

export default function App() {
  const [token, setToken] = useState("");
  const [tenantId, setTenantId] = useState("tenant-acme");
  const [source, setSource] = useState("FastAPI service for coding assessments with Moodle sync and evidence replay.");
  const [draft, setDraft] = useState(null);
  const [session, setSession] = useState(null);
  const [replay, setReplay] = useState(null);
  const [ghost, setGhost] = useState(null);
  const [identity, setIdentity] = useState(null);
  const [learnerId, setLearnerId] = useState("learner-1");
  const [assignmentId, setAssignmentId] = useState("assignment-1");
  const [eventsJson, setEventsJson] = useState(JSON.stringify(SAMPLE_EVENTS, null, 2));
  const [message, setMessage] = useState("Ready");

  async function withAction(label, action) {
    try {
      const result = await action();
      setMessage(`${label}: success`);
      return result;
    } catch (error) {
      setMessage(`${label}: ${error.message}`);
      return null;
    }
  }

  return (
    <div className="page">
      <header>
        <h1>Academic Ops App</h1>
        <p>Context Bridge, Evidence Player, and Ghost Persona operations.</p>
      </header>

      <section className="panel controls">
        <input value={tenantId} onChange={(event) => setTenantId(event.target.value)} placeholder="Tenant ID" />
        <input value={token} onChange={(event) => setToken(event.target.value)} placeholder="Bearer token" />
        <button onClick={() => withAction("Load identity", async () => setIdentity(await getAuthMe(token)))}>
          Load Identity
        </button>
      </section>

      <section className="panel">
        <h3>Context Bridge</h3>
        <textarea value={source} onChange={(event) => setSource(event.target.value)} />
        <div className="controls">
          <button
            onClick={() =>
              withAction("Generate draft", async () =>
                setDraft(
                  await generateContextDraft(
                    {
                      tenant_id: tenantId,
                      source_type: "readme",
                      source,
                      title_hint: "Generated by Academic Ops",
                      level: "intermediate",
                    },
                    token,
                  ),
                ),
              )
            }
          >
            Generate Draft
          </button>
          <button
            disabled={!draft?.draft_id}
            onClick={() =>
              withAction("Submit review", async () =>
                setDraft(await submitDraftReview(draft.draft_id, token, tenantId)),
              )
            }
          >
            Submit Review
          </button>
          <button
            disabled={!draft?.draft_id}
            onClick={() =>
              withAction("Approve draft", async () =>
                setDraft(await approveDraft(draft.draft_id, token, tenantId)),
              )
            }
          >
            Approve Draft
          </button>
        </div>
      </section>

      <section className="panel">
        <h3>Evidence Player</h3>
        <div className="controls">
          <input value={learnerId} onChange={(event) => setLearnerId(event.target.value)} placeholder="Learner ID" />
          <input value={assignmentId} onChange={(event) => setAssignmentId(event.target.value)} placeholder="Assignment ID" />
        </div>
        <textarea value={eventsJson} onChange={(event) => setEventsJson(event.target.value)} />
        <div className="controls">
          <button
            onClick={() =>
              withAction("Ingest evidence", async () => {
                const events = JSON.parse(eventsJson);
                const response = await ingestEvidence(
                  {
                    tenant_id: tenantId,
                    learner_id: learnerId,
                    assignment_id: assignmentId,
                    events,
                  },
                  token,
                  tenantId,
                );
                setSession(response);
                return response;
              })
            }
          >
            Ingest Session
          </button>
          <button
            disabled={!session?.session_id}
            onClick={() =>
              withAction("Replay evidence", async () =>
                setReplay(await replayEvidence(session.session_id, token, tenantId)),
              )
            }
          >
            Replay Timeline
          </button>
          <button
            onClick={() =>
              withAction("Run ghost cheater", async () =>
                setGhost(
                  await runGhostPersona(
                    {
                      tenant_id: tenantId,
                      learner_id: learnerId,
                      assignment_id: assignmentId,
                      persona: "cheater",
                    },
                    token,
                    tenantId,
                  ),
                ),
              )
            }
          >
            Run Ghost Persona
          </button>
        </div>
      </section>

      <section className="grid">
        <article className="panel"><h3>Status</h3><p>{message}</p></article>
        <article className="panel"><h3>Identity</h3><pre>{identity ? JSON.stringify(identity, null, 2) : "-"}</pre></article>
        <article className="panel"><h3>Draft</h3><pre>{draft ? JSON.stringify(draft, null, 2) : "-"}</pre></article>
        <article className="panel"><h3>Evidence Session</h3><pre>{session ? JSON.stringify(session, null, 2) : "-"}</pre></article>
        <article className="panel"><h3>Replay Output</h3><pre>{replay ? JSON.stringify(replay, null, 2) : "-"}</pre></article>
        <article className="panel"><h3>Ghost Output</h3><pre>{ghost ? JSON.stringify(ghost, null, 2) : "-"}</pre></article>
      </section>
    </div>
  );
}
