#!/usr/bin/env bash

set -euo pipefail

BASE="${1:-http://localhost:8000}"
TENANT_ID="${2:-tenant-acme}"
OUT_DIR="${3:-/tmp/moodle_uat}"

mkdir -p "$OUT_DIR"

req() {
  local name="$1"
  local method="$2"
  local url="$3"
  local payload="${4:-}"

  local out_file="$OUT_DIR/${name}.json"
  local code_file="$OUT_DIR/${name}.code"

  if [[ -n "$payload" ]]; then
    curl -sS --max-time 30 -o "$out_file" -w '%{http_code}' -X "$method" "$url" -H 'Content-Type: application/json' -H "x-tenant-id: $TENANT_ID" -d "$payload" > "$code_file"
  else
    curl -sS --max-time 30 -o "$out_file" -w '%{http_code}' -X "$method" "$url" -H "x-tenant-id: $TENANT_ID" > "$code_file"
  fi
}

code_of() {
  tr -d '\n' < "$OUT_DIR/$1.code"
}

json_get() {
  local path="$1"
  local expr="$2"
  python3 - "$path" "$expr" <<'PY'
import json
import sys

path, expr = sys.argv[1], sys.argv[2]
obj = json.load(open(path, "r", encoding="utf-8"))
for part in expr.split("."):
    if not part:
        continue
    if part.endswith("]") and "[" in part:
        key, idx = part[:-1].split("[", 1)
        if key:
            obj = obj.get(key, [])
        obj = obj[int(idx)]
    else:
        if isinstance(obj, dict):
            obj = obj.get(part)
        else:
            obj = None
            break
if obj is None:
    sys.exit(1)
print(obj)
PY
}

summary_line() {
  local name="$1"
  echo "$name $(code_of "$name")" >> "$OUT_DIR/summary.txt"
}

: > "$OUT_DIR/summary.txt"

echo "Running Moodle connector UAT against $BASE (tenant=$TENANT_ID)"

req health GET "$BASE/health"
summary_line health

req catalogue POST "$BASE/connectors/moodle/catalogue/lookup" '{"query":"","include_sections":false,"limit":10}'
summary_line catalogue

CATALOGUE_CODE="$(code_of catalogue)"
if [[ "$CATALOGUE_CODE" != "200" ]]; then
  echo "Catalogue lookup failed; inspect $OUT_DIR/catalogue.json"
  cat "$OUT_DIR/summary.txt"
  exit 1
fi

COURSE_ID=""
if python3 - <<'PY' "$OUT_DIR/catalogue.json"
import json,sys
obj=json.load(open(sys.argv[1],"r",encoding="utf-8"))
items=obj.get("items",[])
sys.exit(0 if items else 1)
PY
then
  COURSE_ID="$(json_get "$OUT_DIR/catalogue.json" 'items[0].id')"
fi

if [[ -z "$COURSE_ID" ]]; then
  echo "No courses returned from catalogue lookup; stopping before provision tests."
  cat "$OUT_DIR/summary.txt"
  exit 0
fi

req users POST "$BASE/connectors/moodle/users/lookup" '{"query":"a","limit":10}'
summary_line users

req cohorts POST "$BASE/connectors/moodle/cohorts/lookup" '{"query":"","limit":10}'
summary_line cohorts

USER_ID=""
COHORT_ID=""
if python3 - <<'PY' "$OUT_DIR/users.json"
import json,sys
obj=json.load(open(sys.argv[1],"r",encoding="utf-8"))
items=obj.get("items",[])
sys.exit(0 if items else 1)
PY
then
  USER_ID="$(json_get "$OUT_DIR/users.json" 'items[0].id')"
fi

if python3 - <<'PY' "$OUT_DIR/cohorts.json"
import json,sys
obj=json.load(open(sys.argv[1],"r",encoding="utf-8"))
items=obj.get("items",[])
sys.exit(0 if items else 1)
PY
then
  COHORT_ID="$(json_get "$OUT_DIR/cohorts.json" 'items[0].id')"
fi

PROVISION_PAYLOAD=$(cat <<JSON
{"course_id":$COURSE_ID,"activities":[{"title":"UAT Practice Activity","activity_type":"practice","delivery_mode":"individual","week":1,"day":1,"topic":"UAT Topic","section_name":"Week 1: UAT","instructions":"Generated by Moodle UAT script"}],"user_ids":[${USER_ID:-}],"role_id":5,"dry_run":true}
JSON
)

# Normalize empty user_ids list when USER_ID is unavailable.
if [[ -z "$USER_ID" ]]; then
  PROVISION_PAYLOAD='{"course_id":'"$COURSE_ID"',"activities":[{"title":"UAT Practice Activity","activity_type":"practice","delivery_mode":"individual","week":1,"day":1,"topic":"UAT Topic","section_name":"Week 1: UAT","instructions":"Generated by Moodle UAT script"}],"user_ids":[],"role_id":5,"dry_run":true}'
fi

req provision POST "$BASE/connectors/moodle/courses/provision" "$PROVISION_PAYLOAD"
summary_line provision

if [[ -n "$COHORT_ID" ]]; then
  req cohort_sync POST "$BASE/connectors/moodle/cohorts/sync-course" "{\"cohort_id\":$COHORT_ID,\"course_id\":$COURSE_ID,\"role_id\":5,\"dry_run\":true}"
  summary_line cohort_sync
fi

PUBLISH_PAYLOAD='{"course_id":'"$COURSE_ID"',"activities":[{"title":"UAT Publish Activity","activity_type":"assessment","delivery_mode":"individual","week":1,"topic":"Publish UAT"}],"dry_run":true}'
if [[ -n "$COHORT_ID" ]]; then
  PUBLISH_PAYLOAD='{"course_id":'"$COURSE_ID"',"cohort_id":'"$COHORT_ID"',"activities":[{"title":"UAT Publish Activity","activity_type":"assessment","delivery_mode":"individual","week":1,"topic":"Publish UAT"}],"dry_run":true}'
fi

req publish POST "$BASE/connectors/moodle/publish" "$PUBLISH_PAYLOAD"
summary_line publish

if [[ "$(code_of publish)" == "200" ]]; then
  REQUEST_ID=""
  if python3 - <<'PY' "$OUT_DIR/publish.json"
import json,sys
obj=json.load(open(sys.argv[1],"r",encoding="utf-8"))
sys.exit(0 if obj.get("request_id") else 1)
PY
  then
    REQUEST_ID="$(json_get "$OUT_DIR/publish.json" 'request_id')"
    req publish_history GET "$BASE/connectors/moodle/publish/history?limit=5"
    summary_line publish_history
    req publish_detail GET "$BASE/connectors/moodle/publish/history/$REQUEST_ID"
    summary_line publish_detail
  fi
fi

echo "Moodle connector UAT complete."
cat "$OUT_DIR/summary.txt"
